// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pb/devicemanager/devicemanager.proto

package devicemanager_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceCreateRequest struct {
	DeviceID             string   `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCreateRequest) Reset()         { *m = DeviceCreateRequest{} }
func (m *DeviceCreateRequest) String() string { return proto.CompactTextString(m) }
func (*DeviceCreateRequest) ProtoMessage()    {}
func (*DeviceCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06fa317f392830, []int{0}
}

func (m *DeviceCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCreateRequest.Unmarshal(m, b)
}
func (m *DeviceCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCreateRequest.Marshal(b, m, deterministic)
}
func (m *DeviceCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCreateRequest.Merge(m, src)
}
func (m *DeviceCreateRequest) XXX_Size() int {
	return xxx_messageInfo_DeviceCreateRequest.Size(m)
}
func (m *DeviceCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCreateRequest proto.InternalMessageInfo

func (m *DeviceCreateRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type DeviceCreateResponse struct {
	DeviceID             string   `protobuf:"bytes,1,opt,name=DeviceID,proto3" json:"DeviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCreateResponse) Reset()         { *m = DeviceCreateResponse{} }
func (m *DeviceCreateResponse) String() string { return proto.CompactTextString(m) }
func (*DeviceCreateResponse) ProtoMessage()    {}
func (*DeviceCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06fa317f392830, []int{1}
}

func (m *DeviceCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCreateResponse.Unmarshal(m, b)
}
func (m *DeviceCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCreateResponse.Marshal(b, m, deterministic)
}
func (m *DeviceCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCreateResponse.Merge(m, src)
}
func (m *DeviceCreateResponse) XXX_Size() int {
	return xxx_messageInfo_DeviceCreateResponse.Size(m)
}
func (m *DeviceCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCreateResponse proto.InternalMessageInfo

func (m *DeviceCreateResponse) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type GatewayCreateRequest struct {
	GatewayID            string   `protobuf:"bytes,1,opt,name=GatewayID,proto3" json:"GatewayID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayCreateRequest) Reset()         { *m = GatewayCreateRequest{} }
func (m *GatewayCreateRequest) String() string { return proto.CompactTextString(m) }
func (*GatewayCreateRequest) ProtoMessage()    {}
func (*GatewayCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06fa317f392830, []int{2}
}

func (m *GatewayCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayCreateRequest.Unmarshal(m, b)
}
func (m *GatewayCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayCreateRequest.Marshal(b, m, deterministic)
}
func (m *GatewayCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayCreateRequest.Merge(m, src)
}
func (m *GatewayCreateRequest) XXX_Size() int {
	return xxx_messageInfo_GatewayCreateRequest.Size(m)
}
func (m *GatewayCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayCreateRequest proto.InternalMessageInfo

func (m *GatewayCreateRequest) GetGatewayID() string {
	if m != nil {
		return m.GatewayID
	}
	return ""
}

type GatewayCreateResponse struct {
	GatewayID            string   `protobuf:"bytes,1,opt,name=GatewayID,proto3" json:"GatewayID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GatewayCreateResponse) Reset()         { *m = GatewayCreateResponse{} }
func (m *GatewayCreateResponse) String() string { return proto.CompactTextString(m) }
func (*GatewayCreateResponse) ProtoMessage()    {}
func (*GatewayCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc06fa317f392830, []int{3}
}

func (m *GatewayCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GatewayCreateResponse.Unmarshal(m, b)
}
func (m *GatewayCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GatewayCreateResponse.Marshal(b, m, deterministic)
}
func (m *GatewayCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GatewayCreateResponse.Merge(m, src)
}
func (m *GatewayCreateResponse) XXX_Size() int {
	return xxx_messageInfo_GatewayCreateResponse.Size(m)
}
func (m *GatewayCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GatewayCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GatewayCreateResponse proto.InternalMessageInfo

func (m *GatewayCreateResponse) GetGatewayID() string {
	if m != nil {
		return m.GatewayID
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceCreateRequest)(nil), "devicemanager_pb.DeviceCreateRequest")
	proto.RegisterType((*DeviceCreateResponse)(nil), "devicemanager_pb.DeviceCreateResponse")
	proto.RegisterType((*GatewayCreateRequest)(nil), "devicemanager_pb.GatewayCreateRequest")
	proto.RegisterType((*GatewayCreateResponse)(nil), "devicemanager_pb.GatewayCreateResponse")
}

func init() {
	proto.RegisterFile("internal/pb/devicemanager/devicemanager.proto", fileDescriptor_cc06fa317f392830)
}

var fileDescriptor_cc06fa317f392830 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x48, 0xd2, 0x4f, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xcd, 0x4d,
	0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0x42, 0xe5, 0xe9, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x09, 0xa0,
	0x08, 0xc6, 0x17, 0x24, 0x29, 0x19, 0x72, 0x09, 0xbb, 0x80, 0xc5, 0x9c, 0x8b, 0x52, 0x13, 0x4b,
	0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x20, 0xc2, 0x9e, 0x2e,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x70, 0xbe, 0x92, 0x11, 0x97, 0x08, 0xaa, 0x96, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xbc, 0x7a, 0x4c, 0xb8, 0x44, 0xdc, 0x13, 0x4b, 0x52, 0xcb, 0x13,
	0x2b, 0x51, 0xed, 0x91, 0xe1, 0xe2, 0x84, 0x8a, 0xc3, 0x35, 0x21, 0x04, 0x94, 0x4c, 0xb9, 0x44,
	0xd1, 0x74, 0x41, 0xad, 0xc2, 0xab, 0xcd, 0xe8, 0x3a, 0x23, 0xcc, 0x85, 0xbe, 0x10, 0x8f, 0x06,
	0xa7, 0x16, 0x81, 0x78, 0x42, 0xb1, 0x5c, 0x3c, 0xc8, 0x2e, 0x17, 0x52, 0xd5, 0x43, 0x0f, 0x0f,
	0x3d, 0x2c, 0x81, 0x21, 0xa5, 0x46, 0x48, 0x19, 0xd4, 0x55, 0x09, 0x5c, 0xbc, 0x28, 0xce, 0x15,
	0xc2, 0xa2, 0x11, 0x5b, 0x28, 0x48, 0xa9, 0x13, 0x54, 0x07, 0xb1, 0x21, 0x89, 0x0d, 0x1c, 0x8d,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x39, 0x33, 0x83, 0xf7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DeviceManagerServiceClient is the client API for DeviceManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeviceManagerServiceClient interface {
	DeviceCreate(ctx context.Context, in *DeviceCreateRequest, opts ...grpc.CallOption) (*DeviceCreateResponse, error)
	GatewayCreate(ctx context.Context, in *GatewayCreateRequest, opts ...grpc.CallOption) (*GatewayCreateResponse, error)
}

type deviceManagerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeviceManagerServiceClient(cc *grpc.ClientConn) DeviceManagerServiceClient {
	return &deviceManagerServiceClient{cc}
}

func (c *deviceManagerServiceClient) DeviceCreate(ctx context.Context, in *DeviceCreateRequest, opts ...grpc.CallOption) (*DeviceCreateResponse, error) {
	out := new(DeviceCreateResponse)
	err := c.cc.Invoke(ctx, "/devicemanager_pb.DeviceManagerService/DeviceCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceManagerServiceClient) GatewayCreate(ctx context.Context, in *GatewayCreateRequest, opts ...grpc.CallOption) (*GatewayCreateResponse, error) {
	out := new(GatewayCreateResponse)
	err := c.cc.Invoke(ctx, "/devicemanager_pb.DeviceManagerService/GatewayCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceManagerServiceServer is the server API for DeviceManagerService service.
type DeviceManagerServiceServer interface {
	DeviceCreate(context.Context, *DeviceCreateRequest) (*DeviceCreateResponse, error)
	GatewayCreate(context.Context, *GatewayCreateRequest) (*GatewayCreateResponse, error)
}

// UnimplementedDeviceManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDeviceManagerServiceServer struct {
}

func (*UnimplementedDeviceManagerServiceServer) DeviceCreate(ctx context.Context, req *DeviceCreateRequest) (*DeviceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeviceCreate not implemented")
}
func (*UnimplementedDeviceManagerServiceServer) GatewayCreate(ctx context.Context, req *GatewayCreateRequest) (*GatewayCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GatewayCreate not implemented")
}

func RegisterDeviceManagerServiceServer(s *grpc.Server, srv DeviceManagerServiceServer) {
	s.RegisterService(&_DeviceManagerService_serviceDesc, srv)
}

func _DeviceManagerService_DeviceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServiceServer).DeviceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicemanager_pb.DeviceManagerService/DeviceCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServiceServer).DeviceCreate(ctx, req.(*DeviceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceManagerService_GatewayCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceManagerServiceServer).GatewayCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/devicemanager_pb.DeviceManagerService/GatewayCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceManagerServiceServer).GatewayCreate(ctx, req.(*GatewayCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeviceManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "devicemanager_pb.DeviceManagerService",
	HandlerType: (*DeviceManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeviceCreate",
			Handler:    _DeviceManagerService_DeviceCreate_Handler,
		},
		{
			MethodName: "GatewayCreate",
			Handler:    _DeviceManagerService_GatewayCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pb/devicemanager/devicemanager.proto",
}
